/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class admin_jadwal extends javax.swing.JFrame {

    /**
     * Creates new form admin_jadwal
     */
    
    private final Connection conn;
    /**
     * Creates new form admin_kota
     */
    private DefaultTableModel tabmode;

    protected void aktif() {
        txtIdJadwal.setEnabled(true);
        txtKeberangkatan.setEnabled(true);
        txtKedatangan.setEnabled(true);
        txtHarga.setEnabled(true);
    }

    protected void kosong() {
        txtIdJadwal.setText("");
        txtKeberangkatan.setText("");
        txtKedatangan.setText("");
        txtHarga.setText("");
    }

    public admin_jadwal() throws SQLException {
        this.conn = config.configDB();
        initComponents();
        
        datatable();
    }

    protected void datatable() {
        Object[] Baris = {"ID_JADWAL", "BUS", "KOTA_AWAL", "KOTA_TUJUAN", "KEBERANGKATAN", "KEDATANGAN", "HARGA"};
        tabmode = new DefaultTableModel(null, Baris);
        tbl_jadwal.setModel(tabmode);
        String sql = "select * from jadwal1";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String id_jadwal = hasil.getString("ID_JADWAL");
                String bus = hasil.getString("BUS");
                String kota_awal = hasil.getString("KOTA_AWAL");
                String kota_tujuan = hasil.getString("KOTA_TUJUAN");
                String keberangkatan = hasil.getString("KEBERANGKATAN");
                String kedatangan = hasil.getString("KEDATANGAN");
                String harga = hasil.getString("HARGA");

                String[] data = {id_jadwal, bus, kota_awal, kota_tujuan, keberangkatan, kedatangan, harga};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }
    public void databus(){   
        try{
            
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            
            String sql = "SELECT * FROM bus WHERE ID_BUS = '"+ kode_bus.getText() +"'";
            java.sql.ResultSet res;
            res = stm.executeQuery(sql);
            while (res.next()) {
                nama_bus.setText(res.getString("BUS"));
            }
               
            
        }catch(SQLException err){
           JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    public void datakotaawal(){   
        try{
            
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            
            String sql = "SELECT * FROM kota WHERE ID_KOTA = '"+ idkotaawal.getText() +"'";
            java.sql.ResultSet res;
            res = stm.executeQuery(sql);
            while (res.next()) {
                kota_awal.setText(res.getString("KOTA"));
            }
               
            
        }catch(SQLException err){
           JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    public void datakotatuju(){   
        try{
            
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            
            String sql = "SELECT * FROM kota WHERE ID_KOTA = '"+ idkotatuju.getText() +"'";
            java.sql.ResultSet res;
            res = stm.executeQuery(sql);
            while (res.next()) {
                kota_tujuan.setText(res.getString("KOTA"));
            }
               
            
        }catch(SQLException err){
           JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblJadwal = new javax.swing.JLabel();
        lblIDJadwal = new javax.swing.JLabel();
        lblIDBus = new javax.swing.JLabel();
        lblKotaAwal = new javax.swing.JLabel();
        lblKotaTujuan = new javax.swing.JLabel();
        lblKeberangkatan = new javax.swing.JLabel();
        lblKedatangan = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        txtIdJadwal = new javax.swing.JTextField();
        txtKeberangkatan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        txtKedatangan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nama_bus = new javax.swing.JTextField();
        kota_awal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kota_tujuan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kode_bus = new javax.swing.JTextField();
        idkotaawal = new javax.swing.JTextField();
        idkotatuju = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_jadwal = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblJadwal.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        lblJadwal.setText("JADWAL BUS");

        lblIDJadwal.setText("ID Jadwal");

        lblIDBus.setText("Kode Bus");

        lblKotaAwal.setText("Id Kota");

        lblKotaTujuan.setText("Id Kota");

        lblKeberangkatan.setText("Keberangkatan");

        lblKedatangan.setText("Kedatangan");

        lblHarga.setText("Harga");

        btnTambah.setBackground(new java.awt.Color(102, 153, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(102, 153, 255));
        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(102, 153, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(102, 153, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Bus");

        nama_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_busActionPerformed(evt);
            }
        });

        kota_awal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kota_awalActionPerformed(evt);
            }
        });

        jLabel3.setText("Kota Awal");

        kota_tujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kota_tujuanActionPerformed(evt);
            }
        });

        jLabel4.setText("Kota Tujuan");

        kode_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kode_busKeyReleased(evt);
            }
        });

        idkotaawal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idkotaawalKeyReleased(evt);
            }
        });

        idkotatuju.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idkotatujuKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUbah)
                        .addGap(46, 46, 46)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addContainerGap(177, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKotaAwal)
                                    .addComponent(lblIDBus)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kota_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kode_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idkotaawal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblIDJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKeberangkatan)
                                    .addComponent(lblKedatangan)
                                    .addComponent(lblHarga))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKedatangan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKeberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(lblKotaTujuan))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idkotatuju, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kota_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 69, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(lblJadwal)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblIDJadwal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKotaTujuan)
                            .addComponent(idkotatuju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kota_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblIDBus)
                                .addComponent(kode_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKeberangkatan)
                                    .addComponent(txtKeberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKedatangan)
                                    .addComponent(txtKedatangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKotaAwal)
                                    .addComponent(idkotaawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHarga)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kota_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(nama_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambah)
                        .addComponent(btnHapus)
                        .addComponent(btnClear))
                    .addComponent(btnUbah))
                .addContainerGap())
        );

        tbl_jadwal.setBackground(new java.awt.Color(204, 204, 255));
        tbl_jadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_jadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_jadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_jadwal);

        btnExit.setBackground(new java.awt.Color(102, 153, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String sql = "insert into jadwal1 values (?,?,?,?,?,?,?)";
        String bus = String.valueOf(nama_bus.getText());
        String kotaawal = String.valueOf(kota_awal.getText());
        String kotatujuan = String.valueOf(kota_tujuan.getText());
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtIdJadwal.getText());
            stat.setString(2, nama_bus.getText());
            stat.setString(3, kota_awal.getText());
            stat.setString(4, kota_tujuan.getText());
            stat.setString(5, txtKeberangkatan.getText());
            stat.setString(6, txtKedatangan.getText());
            stat.setString(7, txtHarga.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN");
            kosong();
            txtIdJadwal.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN" + e);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            String bus = String.valueOf(kode_bus.getText());
        String kotaawal = String.valueOf(idkotaawal.getText());
        String kotatujuan = String.valueOf(idkotatuju.getText());
            String sql = "update jadwal set BUS=?, KOTA_AWAL=?, "
                    + "KOTA_TUJUAN=?, KEBERANGKATAN=?, KEDATANGAN=?, HARGA=? where ID_JADWAL='" + txtIdJadwal.getText() + "'";
            //String sql = "update jadwal set JADWAL=?"
            // + "where ID_JADWAL='"+txtIdJadwal.getText()+"'";

            PreparedStatement stat = conn.prepareStatement(sql);
            //stat.setString(1, txtIdJadwal.getText());
            stat.setString(1, nama_bus.getText());
            stat.setString(3, kota_awal.getText());
            stat.setString(4, kota_tujuan.getText());
            stat.setString(4, txtKeberangkatan.getText());
            stat.setString(5, txtKedatangan.getText());
            stat.setString(6, txtHarga.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUBAH");
            kosong();
            txtIdJadwal.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DIUBAH" + e);
        }

    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "YAKIN MAU HAPUS?", "PESAN KONFIRMASI", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            String sql = "delete from jadwal1 where ID_JADWAL = '" + txtIdJadwal.getText() + "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIHAPUS");
                kosong();
                txtIdJadwal.requestFocus();
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus" + e);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tbl_jadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_jadwalMouseClicked
        int bar = tbl_jadwal.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        txtIdJadwal.setText(a);
        txtIdJadwal.setEnabled(false);
        nama_bus.setText(b);
        kota_awal.setText(c);
        kota_tujuan.setText(d);
        txtKeberangkatan.setText(e);
        txtKedatangan.setText(f);
        txtHarga.setText(g);
    }//GEN-LAST:event_tbl_jadwalMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtIdJadwal.setText("");
        txtKeberangkatan.setText("");
        txtKedatangan.setText("");
        txtHarga.setText("");
        txtIdJadwal.setEnabled(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        menu_admin k = null;
        k = new menu_admin();
        this.dispose();
        k.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void nama_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_busActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_busActionPerformed

    private void kota_awalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kota_awalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kota_awalActionPerformed

    private void kota_tujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kota_tujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kota_tujuanActionPerformed

    private void kode_busKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_busKeyReleased
        // TODO add your handling code here:
        databus();
    }//GEN-LAST:event_kode_busKeyReleased

    private void idkotaawalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idkotaawalKeyReleased
        // TODO add your handling code here:
        datakotaawal();
    }//GEN-LAST:event_idkotaawalKeyReleased

    private void idkotatujuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idkotatujuKeyReleased
        // TODO add your handling code here:
        datakotatuju();
    }//GEN-LAST:event_idkotatujuKeyReleased
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new admin_jadwal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(admin_jadwal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField idkotaawal;
    private javax.swing.JTextField idkotatuju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kode_bus;
    private javax.swing.JTextField kota_awal;
    private javax.swing.JTextField kota_tujuan;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIDBus;
    private javax.swing.JLabel lblIDJadwal;
    private javax.swing.JLabel lblJadwal;
    private javax.swing.JLabel lblKeberangkatan;
    private javax.swing.JLabel lblKedatangan;
    private javax.swing.JLabel lblKotaAwal;
    private javax.swing.JLabel lblKotaTujuan;
    private javax.swing.JTextField nama_bus;
    private javax.swing.JTable tbl_jadwal;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdJadwal;
    private javax.swing.JTextField txtKeberangkatan;
    private javax.swing.JTextField txtKedatangan;
    // End of variables declaration//GEN-END:variables
}
